site_name: My Docs
theme: material
nav:
  - Home: index.md
  - Personas for Learners and Creators: user-personas-learners-creators.md
  - Personas for Library Creators and Code Sharers: user-personas-packaging.md
  - Challenges today: challenges-today.md
  - Unique opportunity: unique-opportunity.md
  - rye: rye-notes.md
  - pixi: pixi-notes.md
  - windows: windows.md
