site_name: My Docs
theme: material
nav:
  - Home: index.md
  - User stories - consumers: users-consumers.md
  - User stories - producers: users-producers.md
  - Challenges today: challenges-today.md
  - How to install Python in 2024: install-python.md
  - Unique opportunity: unique-opportunity.md
  - rye: rye-notes.md
  - pixi: pixi-notes.md
  - windows: windows.md
  - ideas:  ideas.md
  